/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "bygfoot.h"

GtkWidget* create_window_bets (Bygfoot *bygfoot);
GtkWidget* create_window_splash (Bygfoot *bygfoot);
GtkWidget* create_window_alr (Bygfoot *bygfoot);
GtkWidget* create_window_news (Bygfoot *bygfoot);
GtkWidget* create_window_strategy (Bygfoot *bygfoot);
