/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "bygfoot_struct.h"

GtkWidget* create_window_startup (Bygfoot *bygfoot);
GtkWidget* create_window_font_sel (Bygfoot *bygfoot);
GtkWidget* create_window_live (Bygfoot *bygfoot);
GtkWidget* create_window_stadium (Bygfoot *bygfoot);
GtkWidget* create_window_file_chooser (Bygfoot *bygfoot);
GtkWidget* create_window_sponsors (Bygfoot *bygfoot);
